### ISSUE TITLE
How to use the API?

### ISSUE THREAD

**Issue by WBB97** [njam/citygml-to-3dtiles#17]
hello, i am a green hand to javascript, can you show me more detail about how to use the api?
I tried to use the webpack to convert the es6 to es5,but it throws lots of error.
Does that make sense?
Looking forward to your reply.
thank you!!!

**Comment by njam** [comment]
@WBB97 are you trying to use the API in the browser or with NodeJS? Why do you convert from es6 to es5?

**Comment by WBB97** [comment]
@njam Yes, i'm planning to run the code in the browser.After the tries, i solved most of the errors which were caused by the webpack.config.js. I 'm still leaning and trying. 
Thanks your reply. 
By the way, any idea of converting huge citygml data  to 3dtiles? Maybe to constructl hierarchical spatial data by adding the octree functions etc(learned from the 3d-tiles-overview.pdf )?

**Comment by njam** [comment]
> Yes, i'm planning to run the code in the browser.After the tries, i solved most of the errors which were caused by the webpack.config.js.

Interesting! I haven't tried it, but I guess it should work.

> any idea of converting huge citygml data to 3dtiles? Maybe to constructl hierarchical spatial data by adding the octree functions etc(learned from the 3d-tiles-overview.pdf )?

I think there are two parts to it, A) Streaming the input XML, and B) Batching the 3DTiles output data, and possibly stitching it together in the end.

Currently the file size is limited by the maximum size of NodeJS' [`Buffer`](https://nodejs.org/api/buffer.html), which is 2GB. For working sets that fit into memory, another way could be to use another data structure which can hold more data.

**Comment by WBB97** [comment]
@njam 
ok, thanks for your reply.
