### ISSUE TITLE
can't display the converted tileset

### ISSUE THREAD

**Issue by yaryaraldebaran** [njam/citygml-to-3dtiles#23]
i've tried the conversion process and when i call the output on cesium html it doesn't show any buildings.
```javascript import Converter from "citygml-to-3dtiles";
let converter = new Converter({
        srsProjections: {'EPSG:28992':'+proj=sterea +lat_0=52.15616055555555 +lon_0=5.38763888888889 +k=0.9999079 +x_0=155000 +y_0=463000 +ellps=bessel +units=m +no_defs',}});
converter.convertFiles('Random3Dcity_2015-03-11/CityGML/LOD2_3_F0.gml', './output3/');
```
and this is the page look 
![Screenshot_20211124_160346](https://user-images.githubusercontent.com/44632064/143207494-2c1a49e0-73eb-4fa9-a18e-1d17764f5bc9.png)
 and here's the html
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <script src="https://cesium.com/downloads/cesiumjs/releases/1.85/Build/Cesium/Cesium.js"></script>
  <link href="https://cesium.com/downloads/cesiumjs/releases/1.85/Build/Cesium/Widgets/widgets.css" rel="stylesheet">
  <link href="style.css" rel="stylesheet">
</head>
<body>
  <div id="measureContainer"></div>
  <div id="cesiumContainer"></div>
  <script>
  Cesium.Ion.defaultAccessToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJkNDIwOGFhZC05NGM1LTRmOGItOTVjMS1kZmZlNDFiNjc1MzciLCJpZCI6MzEwMzgsInNjb3BlcyI6WyJhc3IiLCJnYyJdLCJpYXQiOjE1OTQ3NDAzMjZ9.2VC0njaqUn3Oy4BNOKW06q3qBEWYZlmicucRG5iVgAQ";
  // Grant CesiumJS access to your ion assets
var viewer = new Cesium.Viewer("cesiumContainer");

var tileset = viewer.scene.primitives.add(
  new Cesium.Cesium3DTileset({
    url: 'output3/tileset.json',
  })
);
viewer.zoomTo(tileset);

  </script>
</body>
</html>
```

**Comment by njam** [comment]
Difficult to say without having the data.

Maybe the buildings are too low (below ground), or too high (high in the sky)? Or maybe there's an error in CesiumJS that stops rendering completely.

If you share the data I can take a look.

**Comment by yaryaraldebaran** [comment]
> Difficult to say without having the data.
> 
> Maybe the buildings are too low (below ground), or too high (high in the sky)? Or maybe there's an error in CesiumJS that stops rendering completely.
> 
> If you share the data I can take a look.

how do i share the data to you? can you give me your email address so that i can share my data?

**Comment by njam** [comment]
@yaryaraldebaran you can send it to me via email: reto@retoonline.com
