### ISSUE TITLE
Can you tell me in detail how to use the tool?

### ISSUE THREAD

**Issue by mrsun12** [njam/citygml-to-3dtiles#3]
Hi! I try use it to convert citygml to 3dtiles on windows, but i can not do it, please tell me in detail how to use on window. Thank u!

**Comment by njam** [comment]
Unfortunately I don't know much about Windows.

Here are instructions on how to use this tool on Linux/macOS - to convert the "3dified" CityGML of Delft.

First download and extract the model of Delft:
```
wget 'https://3d.bk.tudelft.nl/download/3dfier/Delft.gml.zip' && unzip Delft.gml.zip
```

Install the conversion script
```
npm install citygml-to-3dtiles
```

Run the conversion:
```
node --experimental-modules --max-old-space-size=10000 node_modules/.bin/citygml-to-3dtiles \
  Delft_3dfier.gml 3dtiles/
```

You will need to ask somebody who knows how to use NodeJS and NPM on Windows to help you with this. Sorry!
