### ISSUE TITLE
How to use it ? SRS in gml

### ISSUE THREAD

**Issue by JkGemma** [njam/citygml-to-3dtiles#6]
Hello,

It would be cool to be able to use your tool, but I got a problem.

When I run :
```
node --max-old-space-size=10000 --experimental-modules ./bin/citygml-to-3dtiles.mjs path/to/file test
```
I get :
```
(node:26499) ExperimentalWarning: The ESM module loader is experimental.
Converting...
Reading CityGML file 1/1...
Found 1 city objects.

Unknown projection name: "EPSG:3943"
```

My SRS in the gml file is writen like that :

```
      <gml:Envelope srsName="EPSG:3943" srsDimension="3">
```

Is it wrong? If yes, I'd like to know how it should be write

Thanks to you!
Jk.

**Comment by JkGemma** [comment]
Nevermind, added the ESPG and it's fine.

**Comment by yaryaraldebaran** [comment]
> Nevermind, added the ESPG and it's fine.

where do you put the ESPG?

**Comment by njam** [comment]
@yaryaraldebaran you can pass the SRS if you use the library programmatically in your own script like this:
https://github.com/njam/citygml-to-3dtiles#option-srsprojections

Alternatively you could download the code, adjust [SRSTranslator.mjs](https://github.com/njam/citygml-to-3dtiles/blob/e98ef71b573e9d5d19b357db192b149dc14d0e20/src/citygml/SRSTranslator.mjs#L82) locally, and then run the local version.

**Comment by yaryaraldebaran** [comment]
thank you for your response, btw how do you get get the SRSname from citygml files? i want to add functionality that user can include the prj file as the SRS for instance i modified from your example 
```javascript
var SRSname = SRSname_from_gml ;
var SRSPRJ = SRS_from_PRJ;
let converter = new Converter({
  srsProjections: {
    '${SRSname}': '${SRSPRJ}',
  }
});
await converter.convertFiles('./input.xml', './output/');
```
i've read your code [here](https://github.com/njam/citygml-to-3dtiles/blob/2ffa3382b0d0525be0721561b2f321455d5284f5/src/citygml/CityNode.mjs) but still haven't figured it out to recode it into my own code

**Comment by njam** [comment]
>  how do you get get the SRSname from citygml files?

The code currently takes the "srsName" attribute of the root element:
```js
      srs = this.selectNode('//@srsName').value
```

This is a simplification though, see https://en.wiki.quality.sig3d.org/index.php/Modeling_Guide_for_3D_Objects_-_Part_1:_Basics_(Rules_for_Validating_GML_Geometries_in_CityGML)#Spatial_Reference_Systems_.28SRS.29
