### ISSUE TITLE
Documentation URL Down

### ISSUE THREAD

**Issue by JkGemma** [njam/citygml-to-3dtiles#7]
Hello, would like to get this file to test the propertiesGetter, but the URL is down, could you provide us a new URL of it ?

http://www.opengis.net/citygml/building/2.0

Thanks !

**Comment by njam** [comment]
This URL is just the XML-namespace-URL for the type "Building" that I'm querying in the example.
I've stored some documentation about CityGML 2.0 in the repo, which should help you:
https://github.com/njam/citygml-to-3dtiles/blob/master/docs/CityGML_2_0_0_UML_diagrams.pdf

Note that there is CityGML 1.0 and 2.0, you need to check what your file is using.
