### ISSUE TITLE
Failed to run the program

### ISSUE THREAD

**Issue by honglzhu** [njam/citygml-to-3dtiles#9]
I did the following:
1: download the zip file and unzip it;
2: npm install -g
3: copied an xml file (i.e.  delft-citygml2.xml) to the current folder; created a new dir a\
4: when running the program as shown below, I got errors:
c:\3dtile\citygml-to-3dtiles-master>node --max-old-space-size=10000   --experimental-modules ./bin/citygml-to-3dtiles.mjs delft-citygml2.xml   a\
(node:19252) ExperimentalWarning: The ESM module loader is experimental.
internal/modules/esm/resolve.js:58
  let url = moduleWrapResolve(specifier, parentURL);
            ^

Error: Cannot find module c:\3dtile\citygml-to-3dtiles-master\src\3dtiles\Material imported from c:\3dtile\citygml-to-3dtiles-master\src\3dtiles\Mesh.mjs
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:58:13)
    at Loader.resolve (internal/modules/esm/loader.js:85:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:188:40)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:42:40)
    at link (internal/modules/esm/module_job.js:41:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
Did I miss something? How could I workaround it?

**Comment by njam** [comment]
@honglzhu I justed fixed an issue with running it on Windows.

Could you check the updated instructions in the readme and let me know if that works for you? Please note that you need to use NodeJS 13.  https://github.com/njam/citygml-to-3dtiles#cli-script

![image](https://user-images.githubusercontent.com/360800/79009085-07ba9780-7b5f-11ea-8b41-05a49b289ce0.png)

**Comment by honglzhu** [comment]
Yes, it fixed the issue. Thank you!
